### ISSUE TITLE
Is there a way to integrate celery async uploads?

### ISSUE THREAD

**Issue by rlam3** [amol-/depot#31]
@amol- 

I'm doing multiple image uploads per POST request via wtforms. I'm trying to enable async background upload. Is there a way to integrate celery async uploads with DEPOT? 
If so could you please provide us with a solution for this? 
I'm currently using Celery with RabbitMQ.

Suggestions would be good too. 

Thanks!

**Comment by rlam3** [comment]
Currently I'm trying to send the file data to celery in the following fashion 

```python 

Deconstructing the file data during form submission

                celery_create_file.delay(
                    file_stream=unicode(doc_file.read(),"ISO-8859-1"),
                    filename=doc_file.filename,
                    name=doc_file.name,
                    content_length=doc_file.content_length,
                    content_type=doc_file.content_type,
                    # headers=json.dumps(doc_file.headers),
                    file_id=file.id
                )
```

```python

Reconstructing file data on celery/worker

@celery.task(default_retry_delay=10, max_retries=5,name='celery_create_file')
def celery_create_file(file_stream=None, filename=None, name=None, content_length=None, content_type=None, headers=None, file_id=None):
    some_stream = StringIO(file_stream)
    some_file = FileStorage(stream=some_stream, filename=filename, name=name, content_type=content_type, content_length=content_length)

    p_file = SAFileModel(
        file = some_file, #<--- Error when setting the file
        file_id = file_id
    )
    p_file.save()

```


```bash
Traceback (most recent call last):
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/depot/middleware.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/XXXX/Projects/MY_APP/MY_APP/users/decorators.py", line 48, in wrapped
    return f(*args, **kwargs)
  File "/Users/XXXX/Projects/MY_APP/MY_APP/file_manager/views.py", line 156, in create_file
    file_id=file.id
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/Users/XXXX/Projects/MY_APP/MY_APP/tasks/upload_tasks.py", line 26, in celery_create_file
    file_id = file_id
  File "/Users/XXXX/Projects/MY_APP/MY_APP/models/saBase.py", line 31, in create
    instance = cls(**kwargs)
  File "<string>", line 4, in __init__
    
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/XXXX/Projects/MY_APP/MY_APP/models/SAMODEL.py", line 63, in __init__
    self.file = file
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 701, in set
    value, old, initiator)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 710, in fire_replace_event
    self._init_append_or_replace_token())
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/sqlalchemy/orm/events.py", line 1609, in wrap
    return fn(target, value, *arg)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/depot/fields/sqlalchemy.py", line 74, in _field_set
    value = upload_type(value, column_type._upload_storage)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/depot/fields/interfaces.py", line 52, in __init__
    self.process_content(content)
  File "/Users/XXXX/Projects/MY_APP/MY_APP/models/uploadedFile.py", line 39, in process_content
    uploaded_image = Image.open(content)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/PIL/Image.py", line 2289, in open
    im = _open_core(fp, filename, prefix)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/PIL/Image.py", line 2275, in _open_core
    im = factory(fp, filename)
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/PIL/ImageFile.py", line 97, in __init__
    self._open()
  File "/Users/XXXX/.virtualenvs/MY_APP/lib/python2.7/site-packages/PIL/ImImagePlugin.py", line 192, in _open
    s.decode('ascii', 'replace'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\x89' in position 0: ordinal not in range(128)
```

**Comment by amol-** [comment]
It's not really clear to me why you are trying to encode an image as `latin-1` but that seems to be the source of all your problems. Also note that is not really a good idea to pass content of a file through the celery broker. You probably want to store it somewhere and pass the reference to it.

**Comment by rlam3** [comment]
@amol- What do you mean store it somewhere and pass the reference to it? A batch of file is coming from the user's end. I don't have access to their system ... I'm trying to obtain the files from the user and apply the thumbnailfilter afterwards with celery. How do you suggest that I store the files?

**Comment by rlam3** [comment]
Possible recommendation for multipart uploads:

http://boto.readthedocs.io/en/latest/s3_tut.html

Using a pool/thread to manage the uploads?

**Comment by rlam3** [comment]
@amol- is there a way for us to use celery async to do the thumnail filters later after the image was uploaded to s3 first? It takes a really long time to apply filters when there are multiple uploads.

**Comment by hz** [comment]
@rlam3 the different workers share the same memory when you use StringIO, so you uploaded some corrupted data to s3.

**Comment by hz** [comment]
@rlam3 as I addressed the issue in [https://github.com/celery/celery/issues/3286](Celery 3286 issue)

**Comment by hz** [comment]
@rlam3 as I addressed the issue in https://github.com/celery/celery/issues/3286

**Comment by hz** [comment]
@rlam3 - if you just started one worker, would it be successful? I noticed that StringIO in different workers share the same memory, it would be corrupted when you started many workers.

**Comment by amol-** [comment]
Using a celery task is perfectly fine, what is usually a bad idea is passing the whole file value through the queue. The message broker is a not a storage system and usually copes pretty bad with big data, that's why you should pass a reference to the file, not the file itself. 

If you want to generate thumbnails asyncrhonously the simplest way is just to use two separated fields for the original image and for the thumbnails, then you can:
 * save the original value into the model ( leaving the thumbnails empty )
 * fire a task with a reference to the model ( the model ID )
 * query the object back
 * get the file from the original image field and assign it to the thumbnails field triggering all the filters you placed on the thumbnails field.

**Comment by rlam3** [comment]
@amol What I am most confused is where should the file be saved prior to me passing the reference to the file? Because to me, the file is on the users' file system not mine. 

And I am expecting the user to upload multiple files. Assuming that there are 10 files per upload request with an average size of 3-4MB per file, that is a large upload which could take some time from the users' end. In addition, thumbnails are created per file due to the custom filter attachment. 
Therefore I would need to do a for loop for each file that has been uploaded and set the field via sqlalchemy depot in order for depot to know where to upload to.

**Comment by amol-** [comment]
> Because to me, the file is on the users' file system not mine.

File is not on user system, if you got a POST or the file through a form the file is now on your server, usually stored as TemporaryFile or whatever depending on the web framework.

What I'm suggesting is to just upload the base-file to S3 (through a specific DEPOT Column) then spawn a celery task to only generate the thumbnails (through a second different DEPOT Column which the value of the original column is assigned) in such case you can pass celery only the ID of the model for which it should generate the thumbnails.

If that is not enough because uploading the original image to S3 still takes too long then you must perform a direct upload from user PC to S3 (see http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html ) and then spawn a celery task with the URL of the uploaded file so that it gets assigned to the DEPOT column
